### ISSUE TITLE
Can't embed the scores

### ISSUE THREAD

**Issue by gansch** [bartkamphorst/fsc-c#1]
Hi Mr. Kamhorst,

I am trying to embed the continuous future self continuity scale into my questionnaire in qualtrics. I was successful in getting an overlapping circle, but I am stuck trying to retrieve the scores in this code. I don't get what the 'id of the moving circle' and the directions that follow.

> Step four: Adding embeddedData fields for storing values
> Go to 'Survey Flow'
> Add a new Embedded Data Field Name that corresponds to the id of the moving circle, with the string '-overlap' appended. With the example code from the previous step, the field name would thus become 'circle-drag-1-overlap'.
> Repeat the previous step, only with the suffix '-distance'. With the example code from the previous step, the field name would thus become 'circle-drag-1-distance'.
> Step five: Check if your setup is working
> Run through your survey and look at the responses.
> If all is well, you'll see embeddedData fields with the values of the FSC-C measure

Thanks!

**Comment by bartkamphorst** [comment]
> I don't get what the 'id of the moving circle' 

@gansch If you look at the HTML that you inserted into your Qualtrics question on step 3, you see that there is one HTML `<div>` element with a property called `id`. In the example code this property is set to the string value 'circle-drag-1'. Assuming you have copied and pasted that same id into your Qualtrics question, you will need to go to 'Survey Flow' in Qualtrics and add two Embedded Data Field Names:
1. `circle-drag-1-overlap`
2. `circle-drag-1-distance`.

If you've set up the CSS and Javascript correctly (don't forget to uncomment the two lines in the javascript that call `Qualtrics.SurveyEngine.setEmbeddedData`) then you should see the values appear in your Qualtrics data.

Hope this helps!

**Comment by bartkamphorst** [comment]
@gansch Did you manage to get it working in the end?

**Comment by gansch** [comment]
Hi Bart,

Thanks for your explanation.
I'm sorry, I have been on vacation and haven't been able to try. I will try
it after the Jan 7th when I get back.

Merry Christmas,
Ben

On Dec 21, 2018 04:45, "Bart Kamphorst" <notifications@github.com> wrote:

@gansch <https://github.com/gansch> Did you manage to get it working in the
end?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bartkamphorst/fsc-c/issues/1#issuecomment-449379719>,
or mute the thread
